### PR TITLE
CarrierSMS SMS Gateway

### PR DESCRIPTION
**Pull request by glenara**
I wrote the CarrierSMS class for SMS text messaging as an alternative to the pay-per-use gateways.
CarrierSMS takes advantage of the user's Mobile Carrier email gateway for sending a text message to their mobile device.

The changes and additions are all inclusive with appropriate modals, helper data and error handling.

It has been fully tested and does not generate any errors.

I have also written an installation script to added CarrierSMS to the current stable version as well as to a dev branch version which was used to add the modifications to this pull.

More information, along with screen shots can be viewed on my site and the installation file is available to anyone wanting to add CarrierSMS to their Server Monitor, current master or dev branch version.
http://CanadianDomainRegistry.ca/contrib/CarrierSMS

I trust you will find all in good order.
Glen

ps.  Do you want me to add the var/values to "all" the lang files?
I wasn't sure if they should be included with the initial pull request since I wouldn't be able to translate them.

### CODE REVIEW

**Comment by sadortun** [comment]
Why do you need an extra profile field for ?

**Comment by glenara** [comment]
This was written last December and your taxing my memory!
As I recall, during my dev stages I had used the 'mobile' field but ran into conflicts or issues with other config/options that didn't mix/work well with the rest of the application.

It's suffice to say I had a good reason for the additional field.

**Review by ITIStudios — COMMENTED** [review]
What "more info" are you looking for?

**Comment by sadortun** [comment]
> Why do you need an extra profile field for ?
I have difficulty to see why this specific carrier need a separated field, but all the other providers can work with the existing schema

**Comment by ITIStudios** [comment]
Just a few things that come to mind are:
<li>the two fields contain different data types (numbers vs text)
<li>To use both would require editing the user's data.  You should be able to use any item from the drop down list with out having to edit the user.
<li>The other conflicts that I mentioned in the first response that I have since forgotten.

**Comment by ITIStudios** [comment]
I have reviewed the 3 conflicting files listed in the "Branch Conflicts..." where or what the problem is.

**Comment by TimZ99** [comment]
Is this still active? Please update to 3.2.0 if so.

**Comment by ITIStudios** [comment]
Pardon!
Why didn’t you add it before releasing 3.2.0
It was a !00% complete and fully functional with no errors and now you want me to redo what I started almost 2 years ago?

If you don't want to give the community FREE SMS then just say so.

**Comment by TimZ99** [comment]
Sorry, maybe it sounded a little hard. I'm just a contributor, not a member so I can't/couldn't merge your pr.
I understand that it's frustrating that you started 2 years ago and nothing has happend.

Just trying to get some pull requests and issues to the next update or closed if the are dead. Reviewing, contributing etc. A Free sms service would be a nice feature.

**Comment by glenara** [comment]
I’m sorry but I do not have time to through re-submitting at this time or any time in the near future.

**Comment by TimZ99** [comment]
Thank you for the pr and time you put in to the project. Too bad that it went this way.

**Comment by glenara** [comment]
Yes, a definite loss for the project/community.
It certainly appears as though there is no interest in Free SMS.

If so, maybe there is someone interested in taking over my work and updating it for the next release.

Good luck with the project.

**Comment by TimZ99** [comment]
Will put it on the list 😉

**Comment by raggoo** [comment]
WOW! Unbelievable!

So just to be clear we all know that we would rather PAY our hard earned money for something rather than to get it FREE and not have to pay right LOL!  

WTF???

**Comment by TimZ99** [comment]
I don't know what happened here and why this was never merged. I wasn't a maintainer at that point and didn't use PSM a lot. 

If you want this free SMS gateway, feel free and update the pr.

**Comment by TimZ99** [comment]
Maybe [here](https://github.com/phpservermon/phpservermon/blob/develop/docs/intro.rst), or [here](https://github.com/phpservermon/phpservermon/blob/develop/docs/faq.rst)

**Pull request closed without merging**
