### PR TITLE
change rtime to numerical to avoid DB update conflicts

### LINKED ISSUE #943: [BUG] ping doesn’t monitor correctly
**Describe the bug**
The ping test uses the first line outputted to mark the test as positive. I tested it with `test.com`, which has the following result:
```
Last positive output:
PING test.com (69.172.200.235) 56(84) bytes of data.
```

Via terminal:
```
 ping test.com
PING test.com (69.172.200.235) 56(84) bytes of data.
^C
--- test.com ping statistics ---
6 packets transmitted, 0 received, 100% packet loss, time 122ms
```

As you can see, there is a 100% package loss but the test in phpservermon describes the server as online.

Additionally, the latency is always `0`.

**To Reproduce**
1. Create a server with domain test.com and type set to ping.
2. Check the details page of this test.

**Expected behavior**
The ping statistics are monitored properly with the correct latency and online/offline flag.
**Version (please complete the following information):**
 - Version 3.5.0
 - PHP 7.3

### PR DESCRIPTION
**Pull request by wienfuchs**
Should completely solve https://github.com/phpservermon/phpservermon/issues/943 - type conflict solved this locally.

### CODE REVIEW

**Comment by wienfuchs** [comment]
@TimZ99 also for "next release" ;)

**Review by TimZ99 — APPROVED** [review]

**Comment by TimZ99** [comment]
;) will do

**Comment by Pofilo** [comment]
Hello !
Is a new version planned soon ?
This ping always UP makes the last version unreliable for newcomers.

**Comment by wienfuchs** [comment]
To me it looks like there is, as actual devel version was raised to "Version 3.6.0.beta2". It's probably a question of - rare - private time availability of volunteer @TimZ99 ;)

**Comment by Pofilo** [comment]
Yeah sure !
Time is the main problem for open source projects, there is absolutely no problem if there is no release this year ;)

**Comment by TimZ99** [comment]
Time, if we only had more. Don't worry, there will absolutely be a new release... this year 😝. Asap.

**Pull request merged**
