### PR TITLE
Adding OVH SMS Gateway.

### PR DESCRIPTION
**Pull request by cyberal77**

### CODE REVIEW

**Comment by cyberal77** [comment]
Just have rebase and sign commit

**Comment by imsoftware** [comment]
Hey, can i test it without an ovh account?

**Comment by cyberal77** [comment]
Hi,

No you can't test without OVH account. However, maybe you can create a account to test service with 20 sms free. But i think you need a french mobile number.

Regards

**Review by TimZ99 — APPROVED** [review]

**Comment by TimZ99** [comment]
Looking good 👍

**Pull request merged**
