### PR TITLE
Adding callr and plivo as sms gateways

### PR DESCRIPTION
**Pull request by matthiaz**

### CODE REVIEW

**Comment by matthiaz** [comment]
also noticed there were a couple of missing translations in the list of gateways, so I added them

**Comment by wardpieters** [comment]
Hi Matthiaz, thanks for you support for this project.

Plivo and Callr both have a HTTP API and that's preferable since we don't have to add as many files and it keeps te project smaller. Only one file for each gateway... I'll try to add both Gateways this evening and keep you posted.

**Comment by matthiaz** [comment]
Hi Ward,

I was already wondering why you did most other integrations without
composer. Sorry about that. I do wonder though what you mean by keeping the
project smaller, composer takes care of the dependencies, so the code
itself shouldn't be included right?

Matthias

2018-05-28 21:12 GMT+02:00 Ward Pieters <notifications@github.com>:

**Comment by wardpieters** [comment]
Hi Matthias, I am not that experienced at using composer. But the libraries you require are still downloaded right? If you're e.g. running this on a Raspberry Pi Zero, this will definitely save you a bit of storage.

**Comment by matthiaz** [comment]
I just meant they wouldn't be in the source on github. But yeah, good
point, they will be downloaded when you actually install the software.
For my use case the extra storage isn't an issue, but I understand the
reasoning.



2018-05-28 21:57 GMT+02:00 Ward Pieters <notifications@github.com>:

**Comment by TimZ99** [comment]
In my use case storage is also not a problem.
But there are cases where every MB counts. By using the REST API's we can keep the size of an integration around 2KB, most Libraries are a lot bigger.

**Pull request closed without merging**
