### PR TITLE
Retain user data in DB for existing users

### LINKED ISSUE #1182: [BUG] User details deleted from database on login via LDAP
**Describe the bug**
User details (name, email, discord, etc.) are deleted from the database on every login via LDAP.

**To Reproduce**
1. Configure LDAP authentication in settings.
2. Login. On first login the username is used as the user's name also.
3. Fill in other details like name, email, mobile, pushover, telegram, webhook, discord, etc.
4. Logout.
5. Login again.

**Expected behavior**
Details already input by the user through the user profile interface must be left unchanged in the database.

**Version (please complete the following information):**
Unreleased

**Additional context**
Only applies for LDAP environments

### PR DESCRIPTION
**Pull request by viharm**
Fixes #1182 .

Although the bulk of the change is in the LDAP auth module ([see this](https://gitlab.com/viharm/PsmLDAPauth/-/merge_requests/13)), a minor change in the User Service is required to revise the call to the LDAP module.

It adds the user information object for assessing what data of the user already exists in the DB.

### CODE REVIEW

**Comment by viharm** [comment]
Hi @TimZ99 , this is a very small change to the User service. Please could you approve?

**Comment by viharm** [comment]
@TimZ99 , @tomhatzer , @sadortun , please could you advise if there is anything else I need to do to support this merge request?

**Comment by viharm** [comment]
Bump

**Review by sadortun — CHANGES_REQUESTED** [review]
Is the new parameter was added to the LDAP library ? If so, Composer minimum requirements should be updated too.

**Comment by viharm** [comment]
> Is the new parameter was added to the LDAP library ? If so, Composer minimum requirements should be updated too.

hi @sadortun , thanks for looking into this.

I noticed that the bot had already picked up the composer version number on my fork.

here… https://github.com/viharm/phpservermon/pull/20

should I let it merge into my branch? Then it all merges into this one PR?

**Comment by sadortun** [comment]
@viharm yes and no, you also need to change `cpmposer.json` version to match the first version where the new parameter were added. Otherwise some user might have a package installed by composer who don't have this parameter

**Comment by viharm** [comment]
Hi @sadortun , just trying to update this. However the `composer.json` already has a caret-based version (specified as `^1.1`). This should be good for all v1.x.x releases of the library (see reference [here](https://getcomposer.org/doc/articles/versions.md#caret-version-range-)). Since the library has been upgraded from `1.1.3` to `1.1.4`, there should really be no change required to composer.json.

I suppose the composer.lock should probably be updated, but that is not a manual change.

Do you agree?

**Comment by viharm** [comment]
Bump

**Comment by viharm** [comment]
Hi @sadortun, please let me know how else I can help.

**Comment by viharm** [comment]
@TimZ99 , @tomhatzer , @sadortun , please could you advise if there is anything else I need to do to support this merge request?

The change in the upstream library was captured by the bot in #1184 .

**Review by sadortun — APPROVED** [review]

**Comment by sadortun** [comment]
@viharm Are you able to sign the commit ? 

Otherwise @TimZ99 will need to update branch protection rules.

**Review by sadortun — APPROVED** [review]

**Comment by sadortun** [comment]
@viharm fyi
Screenshot_20230810-120134

**Comment by viharm** [comment]
> @viharm fyi
> Screenshot_20230810-120134

Thanks, I’ve been reading Guthub docs to understand how to fix this. I will probably add a dummy commit to ensure last commit is signed. If not, we may have to do a fresh pull request.

**Comment by sadortun** [comment]
I think you need to force push or rebase to ensure your old commit get signed

**Comment by viharm** [comment]
Thanks @sadortun , I've finally managed to setup commit signing in my IDE.

I've tried several things (including [this](https://safjan.com/git-sign-commit-n-commits-back/)), but I can't seem to be able to go back and sign the old commit, especially since I've rebased my fork to the latest `develop` branch.

I suggest I create a new branch with the same changes. It's easy to do, since the change is very minor. However this means it will be a new pull request.

Are you ok with this?

**Comment by TimZ99** [comment]
I will make an exception for the unsigned commit. One thing before merging, composer.json should be changed to ^1.1.4. Having 1.1.3 installed will cause errors. I wanted to change it myself, but I don't have the right to do that. If you could change that, I will merge this PR.

Thanks for the fix 😄

**Comment by viharm** [comment]
Hi @TimZ99 , thanks. As for the requirement in `composer.json`, the library is pinned to `^1.1` in `composer.json`, and the bot had updated this in `composer.lock` last year in 4693ff3910074df10bc16178a74da9ca3c4de081. It appears that this was merged in #1184. Hope this is ok.

I've also rebased my branch again from the `develop` branch, hopefully making things a little simpler. Please let me know if this is ok.

**Pull request merged**
