### PR TITLE
Translation fixes for NL language

### PR DESCRIPTION
**Pull request by Southparkfan**

### CODE REVIEW

**Comment by JBlond** [comment]
:+1:

**Comment by ocean123** [comment]
What should there be fixed? Everything is translated, isn't?

**Comment by Southparkfan** [comment]
These are spelling fixes, and consistency fixes.

**Comment by ocean123** [comment]
So, can you upload the fixed language file?

**Comment by Southparkfan** [comment]
This pull request has the fixes. It is only waiting for someone that wants to merge it.

**Comment by ocean123** [comment]
:thumbsup:

**Comment by dopeh** [comment]
Sorry for delays merging the open pull requests. Next couple weeks a new 
version will be released and pull requests will be merged.

On 04-01-16 19:30, Southparkfan wrote:
>
> This pull request has the fixes. It is only waiting for someone that 
> wants to merge it.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/phpservermon/phpservermon/pull/235#issuecomment-168760935>.
>
two
> two

**Pull request merged**
