### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by Quentinvarquet**
Add Docker link

### CODE REVIEW

**Comment by sadortun** [comment]
Good idea, ive added you to the dockers organization for phpservermon. Can you push your image, and update the link in the Readme ?

**Comment by Quentinvarquet** [comment]
Hello,

Are you sure you want to use it from Docker Cloud instead of creating directly an account "phpservermon" on the Docker hub and add me on it ?

**Comment by sadortun** [comment]
Hi @dopeh,
Can you fork the https://github.com/Quentinvarquet/docker-phpservermonitor repo into phpservermonitor organisation ? 

Thanks,
Samuel

**Comment by dopeh** [comment]
Done

**Pull request merged**
