### PR TITLE
Disable directory Listing

### PR DESCRIPTION
**Pull request by elbakai**
Prevent a Directory Listing by using htaccess file

### CODE REVIEW

**Comment by elbakai** [comment]
Prevent a Directory from listing files

**Comment by dopeh** [comment]
Fixed in a slightly different way by adding blank index.html files to the top level dirs.

**Comment by elbakai** [comment]
so with blank index file we should add this file inside all folders, if not it will not work with the subfolder

**Comment by elbakai** [comment]
if we add index.html to the top level dirs it will not block me if i want list the content of this folder static/css, or cron....., so we should add it into all folder for working, nut if we use htaccess files, it will be work if we put it into the top level dir

**Pull request closed without merging**
