### PR TITLE
Updating languages

### PR DESCRIPTION
**Pull request by Laupe**
Editing and updating of the Czech language

### CODE REVIEW

**Comment by sadortun** [comment]
Hi @Laupe Thanks for your PR. Why are you modifying the two png images in https://github.com/phpservermon/phpservermon/pull/285/commits/d7140c9b2a85222eae462e81cc891841ba103f69 ?

**Comment by Laupe** [comment]
@sadortun Ah, you're right ... it is a mistake it's going to return something or ignore?

**Comment by sadortun** [comment]
Ok. I'll not merge the PNG images.

**Comment by Laupe** [comment]
OK thx

**Pull request merged**
