### PR TITLE
Public page

### LINKED ISSUE #51: Option to make status page public
Several users have expressed the wish to make the status page available to the public so it can be embedded on a website.
This would require a toggle in the configuration to enable the public page, and maybe even per-server settings to determine which servers to make public.

### PR DESCRIPTION
**Pull request by TimZ99**
Closes #51 .

6 long years later 🎉

### CODE REVIEW

**Comment by artiomma** [comment]
Hi
I implemented the changes to my environment.
trying to create public user and receive this errors

Only user '\_\_public\_\_' can have the level anonymous.
 You can't remove the last administrator.
 The entered password is invalid.

what i did wrong?
is needed to set password to public user?

**Comment by TimZ99** [comment]
> Only user '__public__' can have the level anonymous.

Make sure you use user` __PUBLIC__` .

> You can't remove the last administrator.

36e33b3 - Already fixed in newer versions, shouldn't have been here.

> The entered password is invalid.
> 
> what i did wrong?
> is needed to set password to public user?


99bcc90 - Removed the password input and generate a password on the background.

**Comment by artiomma** [comment]
Hi
Added user __PUBLIC__ without password.
After then open public.php page
image
is still asking me to enter password

**Comment by artiomma** [comment]
> > Only user '**public**' can have the level anonymous.
> 
> Make sure you use user` __PUBLIC__` .
> 
> > You can't remove the last administrator.
> 
> [36e33b3](https://github.com/phpservermon/phpservermon/commit/36e33b32154c1e803b2a00cc9533822fbcf52a09) - Already fixed in newer versions, shouldn't have been here.
> 
> > The entered password is invalid.
> > what i did wrong?
> > is needed to set password to public user?
> 
> [99bcc90](https://github.com/phpservermon/phpservermon/commit/99bcc90c0325e9f261c80cb3589cfa115211af81) - Removed the password input and generate a password on the background.

Working.
Thank You

**Comment by kennyparsons** [comment]
Just installed 3.6 beta for the slack notifications. Excited to see this PR hit the market!

**Comment by sadortun** [comment]
Thanks @TimZ99

**Pull request merged**
