### PR TITLE
Popular Ports + Default language English

### PR DESCRIPTION
**Pull request by Laupe**
Popular Ports added + added Default language - English

see. Issue #286 and #287 Issue

marge only commits:
1dfa802fb468190476cacbdc0ca09274bad41195
8d5db9edb23385e6b5a1be14426114aea512a1a1

I'm sorry, I accidentally stumbled into something else there. Please ignore it and do marge. Next time profit from :-)

Ignore pls commits:
6ba2e6023be40c528e11d859a9a5ab99a1d12022
5840c5dca5d25fe7bc44fa23a9b7f271fbcaf9da

### CODE REVIEW

**Comment by nurhambali** [comment]
How to adding your ICMP ?

**Comment by sadortun** [comment]
Hi @Laupe  Can you send me an email ( see profile page ) i have a few questions for you

**Comment by Laupe** [comment]
Hi @sadortun  OK, I'll send you an email

**Comment by sadortun** [comment]
Tanks, sent you a message

**Comment by sadortun** [comment]
Commits : 
1dfa802fb468190476cacbdc0ca09274bad41195
8d5db9edb23385e6b5a1be14426114aea512a1a1

Has been chery-picked into develop

Thanks a lot  !

**Pull request closed without merging**
