### PR TITLE
Update Russian language and remove double locale strings from English

### PR DESCRIPTION
**Pull request by Alexell**

### CODE REVIEW

**Review by sadortun — CHANGES_REQUESTED** [review]
Please remove use of tabs and use spaces instead.

**Comment by Alexell** [comment]
I will never use spaces instead of tabs.

**Comment by randy-johnson** [comment]
@Alexell, it wasn't an attack on your coding style.  If the maintainer(s) chose to use spaces, then it would make sense they would want you to do a quick search/replace to convert your tabs to spaces to keep the code uniform.

**Comment by Alexell** [comment]
I still don't know how to add another commit to an already existing Pull Request. I'll make a new one later.

**Pull request closed without merging**
