### PR TITLE
Fix of BUG #853

### PR DESCRIPTION
**Pull request by xsuchy09**
*fix - email_smtp_password is saved encrypted and not as plain text @see https://github.com/phpservermon/phpservermon/issues/853

### CODE REVIEW

**Comment by xsuchy09** [comment]
~~I didn't test it - so better will be to test it :)~~
Tested (just save and read values in config, not using to sending emails - but encrypt method should be there ...). Looks good.

**Comment by xsuchy09** [comment]
I will merge this branch into #852 after this will be in develop. I will change there encryption of field `jabber_password` there via this automatic system (array of encrypted values/inputs).

**Comment by xsuchy09** [comment]
Just notice...I don't think that it is good idea to read and fill inputs with passwords when forms are loaded. My first implementation was not read value to form and save new value just when it is filled. I change it just because of history of this project and possibility to unset password in fast way. Better will be some button or checkbox with delete password possibility. Because filled password input with actual password is not so good idea and is a security risk (change input type to text and you will see actual password ... just a coffee with started pc left and someone can have your password to smtp, jabber, ...).

**Comment by TimZ99** [comment]
@xsuchy09 I agree. Fixed it with ce5485b.

**Review by TimZ99 — APPROVED** [review]

**Pull request merged**
