### PR TITLE
Ignore 401 Unauthorized and 403 Forbidden headers, site is still online.

### PR DESCRIPTION
**Pull request by rjayako**
Fix for phpservermon displaying header 401 and 403 as offline.

### CODE REVIEW

**Comment by ldrrp** [comment]
This should be merge, definately should be ignored. But you may also use string search to avoid this.

**Comment by davyrolink** [comment]
If you're using phpservermon for website monitoring, 401 Unauthorized and 403 Forbidden headers, should trigger a error. I think this should not be merged..

**Comment by elkangaroo** [comment]
It would be really great, if one could specify the valid/expected HTTP Status Code(s) when choosing type = website.

**Comment by sadortun** [comment]
Hi @rjayako,  Thanks for your submission.

Unfortunately, for most users 4xx codes represent an invalid state and should trigger an error. If you are interested, this feature could be accepted as a configuration option. But not as a default behavior. Please submit a new PR with the option to switch on or off this behaviour.

> Design guideline ##9 Obey the principle of least astonishment. Every method should do the least  surprising thing it could, iven its name. If a method doesn't do  what users  think it will, bugs will result.

**Pull request closed without merging**
