### PR TITLE
added updater.sh shell script

### PR DESCRIPTION
**Pull request by petrk94**
This script was made by me, as I got the problem how to update it.
As @TimZ99 helped me how to update #619 , I thought about why not make a update mechanism.
So I wrote this shell script, which identify the latest available version via github API with cURL, download it with wget as update.zip and extract it with unzip.
Afterwards there will some files moved and it tell you that the update was successfully.

Its a script made in a hour, nothing complicated with if etc. so I want to provide this pull request already now and update the script with some more logic like, ready for update? (yes/no), exist vendor directory (for php composer.phar install)

Please check the script, I were glad if you accept my pull request.
Thanks

### CODE REVIEW

**Comment by petrk94** [comment]
@TimZ99 takes that really such long to get the pull request approved?^^

**Comment by TimZ99** [comment]
I had some issues testing the script and ran out of time, so I decided to review at a later time.

**Comment by petrk94** [comment]
@TimZ99 can you tell me what issues you had? Than I can try to reproduce it. The updater script is even not yet perfect, there are still some logic missing to decide whether user is ready for update etc.
I can even write a debug function, if it helps.

**Comment by TimZ99** [comment]
It was a wrong file permission. 
And wget wasn't installed.

**Comment by petrk94** [comment]
@TimZ99 well, you are the first who I notice who has not wget installed on a linux machine by default^^ thanks for updating the if logic for that.
I thought more about to integrate a if logic function, to check whether vendor exist, before running not necessary composer.phar.

**Comment by TimZ99** [comment]
Haha I'm running macOS on this machine. It's missing some parts like wget. 

The vendor folder can stay, but the composer command needs to be set to update then.

**Comment by petrk94** [comment]
ah I see^^
Well than this is explaining it. I could not develop on MacOS. Im writing code on my Windows machine and upload it to run on my linux server.

**Comment by petrk94** [comment]
yes, thats how I imagined it^^
Is it ready now for work?

**Review by TimZ99 — APPROVED** [review]

**Comment by petrk94** [comment]
Any update here?

**Comment by TimZ99** [comment]
I really don't know why I haven't merged this already.

**Comment by TimZ99** [comment]
That's why ^^^

**Comment by petrk94** [comment]
thanks for merging :)

**Pull request merged**
