### PR TITLE
Mark HTTP codes as online #175

### LINKED ISSUE #175: Add option to specify which HTTP status codes are considered as "online"
How do I set header 401 as a Online status and not Offline. Since that doesn't necessarily mean the site is offline. It just means the site required access. Any ideas?

### PR DESCRIPTION
**Pull request by TimZ99**
Closes #175.

Added the option to mark specific HTTP status codes as online.  401 and 403, for example, don't mean that the server is offline.

### CODE REVIEW

**Comment by SciLor** [comment]
I have configured the "400" as allowed. But it still fails on "HTTP/1.1 400 Bad Request".

**Comment by TimZ99** [comment]
Doesn't the check fail because of another test? 
If I test a website with a 400 error, it marks it as online.

**Comment by SciLor** [comment]
I am sure, that it didn't worked because of that. It is a POST in my case. The other check was for a special text. If I inverted the rule (text not in) it still failed, but because of the text. I will log that for you later on.

**Comment by SciLor** [comment]
If pattern is set as offline, Last error shows "TEXT ERROR : Pattern '344' was found."
If I switch it to online it stays on that last error.

**Pull request merged**
