### PR TITLE
Better fit for bigger screens

### LINKED ISSUE #857: [BUG] minor HTML text wrapping issues
**Describe the bug**
On same pages, the text wraps around because the containing element is too small.  There's plenty of space on my screen so this can be fixed easily by increasing the size of the container or by changing the text to take up less space.

on page "server_status", using the default boxy view (instead of the row view), the text that says "Last online: about a minute ago" has the word "ago" on a second line because it doesn't all fit on one line due to the size of the green containing element.  This can be fixed by changing the size of the box or by changing the text to something like "< 1 minute ago" instead of "about a minute ago".

on page "server", the table only fills about 60% of my screen's horizontal space, so several of the table cells have wrapping.  It's very distracting and unnecessary.  Please increase the width of the table so the text doesn't have to wrap.  If you want to make it customizable, maybe each column could have a custom width setting, so the user can specify their own preferred widths.  Those settings should be stored in the database so it persists between docker image updates.

**Expected behavior**
Text should not wrap unless really necessary.  It looks nicer, and is easier and faster to read that way.

**Desktop (please complete the following information):**
 - Version 3.4.5

### PR DESCRIPTION
**Pull request by TimZ99**
Fixes #857.

### CODE REVIEW

**Comment by mateuszmalek** [comment]
@TimZ99 Using `container-fluid` instead of `container` is a good approach. I would consider setting `max-width` (for ex. at 1920px) for `.container-fluid` - I'm using UWQHD (3440x1440) and it looks pretty... strange 😃 

Without `max-width`:
image

With `max-width: 1920px`:
image

I think that a good idea would be to make some changes to navbar too:
image

Just wrap inner HTML of `nav` into `<div class="container-fluid"></div>`.

**Comment by TimZ99** [comment]
You're right, 3000px is a bit to wide. I agree that 1920px looks much beter.

**Review by mateuszmalek — APPROVED** [review]
Looks good for me 👍

**Comment by TimZ99** [comment]
Time to merge then 👍.

**Pull request merged**
