### PR TITLE
Issues 212 pushover

### PR DESCRIPTION
**Pull request by Laupe**
Issues #212 pushover

Please check and marge. 

Please share only commit:
57fb82f469016ca157ce5d4d75fc977deb3f95a3
15fb0c7d4572124c8f5fbf946f68e4f5f39f061b
e03625902a85e9680ee7ca1d92e8b4b80d5339dc
7f76d7f5a8e80d6f1d8e006cb5eabf709128c83e
bc45f53ba2c5289a9c7c59a57049855fab714be5
34e6f9a15790f64761bd0b58427861417bb9f1fb

### CODE REVIEW

**Comment by Laupe** [comment]
Hi @sadortun 

I wanted to ask whether this will marge? I did not want to make yet more changes than this will be done. If I can resolve the conflict.

Thank you

**Comment by Yelles** [comment]
Any news about this ?
I need this feature too 👍 
Regards

**Comment by sadortun** [comment]
@Yelles You can rebase the commits mentioned by Laupe on develop and i'll merge it.

**Comment by tjharman** [comment]
If anyone has a diff for merging this with the current v3.2.0 I'd love to grab a copy.
I don't know how to drive git well enough to merge this, but it looks lovely!

**Pull request closed without merging**
